apiVersion: v1
kind: Secret
metadata:
  name: ghcr-cred
  namespace: geoapi
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: '{"auths":{"ghcr.io":{"username":"your-github-username","password":"your-ghcr-token"}}}'
